version: '3'

services:
  database:
    build: ./database
    image: swt_database
    ports:
      - 3306
    environment:
      MYSQL_USER: root
      MYSQL_PASS: comsc
      STARTUP_SQL: /tmp/SWTSchema.sql
    container_name: swt_db

  server_1:
    build: ./server
    image: swt_server
    links:
      - database
    command: java -jar swt-project-0.0.1-SNAPSHOT.jar --spring.profiles.active=production
    ports:
      - 8080:8080
    container_name: swt_1

